# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Documentation at vagrantup.com.

  config.vm.box = "jessie64.box"
  config.vm.synced_folder "otter-builds", "/home/vagrant/otter-build"

  #config.vm.provision :shell, :path => "scripts/bootstrap.sh"
  # Call with: BUILD_DEB_ARGS='-s test' vagrant provision
  # BUILD_DEB_ARGS='-e "Full Name <email@example.com>"' vagrant provision
  # The single quotes are important.
  config.vm.provision :shell, :path => "scripts/build-otter-deb.sh", args: ENV['BUILD_DEB_ARGS']

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
  end
end
